mysql:
  charset: utf8mb4
  db: way_to_go
  host: localhost
  password: 123456
  user: waytogo
session:
  secret-key: mima
mail:
  smtp: smtp.163.com
  smtp-port: 587
  user: boyan_chan@163.com
  password: ABC123